### ISSUE TITLE
undefined name 'OneDirectionTestModel'

### ISSUE THREAD

**Issue by cclauss** [junyanz/BicycleGAN#1]
flake8 testing of https://github.com/junyanz/BicycleGAN on Python 2.7.14

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./models/models.py:10:17: F821 undefined name 'OneDirectionTestModel'
        model = OneDirectionTestModel()
                ^
```

**Comment by junyanz** [comment]
Fixed.
