### ISSUE TITLE
A resize_ error

### ISSUE THREAD

**Issue by JaheimLee** [junyanz/BicycleGAN#11]
Hello! When I run the test_edges2handbags.sh, I met an error. What's the problem?

model [BiCycleGANModel] was created
Loading model bicycle_gan
process input image 000/010
Traceback (most recent call last):
  File "./test.py", line 41, in <module>
    model.set_input(data)
  File "/home/jaheimlee/gitrep/BicycleGAN/models/base_model.py", line 193, in set_input
    self.input_A.resize_(input_A.size()).copy_(input_A)
RuntimeError: calling resize_ on a tensor that has non-resizable storage. Clone it first or create a new tensor instead.

**Comment by junyanz** [comment]
It should be fixed by the latest commit. Let us know if it works for you.
