### ISSUE TITLE
Should this be real_A_random instead of real_A_encoded?

### ISSUE THREAD

**Issue by samrudhdhirangrej** [junyanz/BicycleGAN#13]
https://github.com/junyanz/BicycleGAN/blob/944a87d55cc441240883679a728a5ce8be0a0db9/models/bicycle_gan_model.py#L64

**Comment by eveningglow** [comment]
I think so too and also in this [line](https://github.com/junyanz/BicycleGAN/blob/5bd76aca5ed3d9e62aebb578a28a1053b622ddf9/models/bicycle_gan_model.py#L54) which is `self.fake_B_random = self.netG.forward(self.real_A_encoded, self.z_random)`, why do you make `self.fake_B_random` using `self.real_A_encoded` not `self.real_A_random`?

**Comment by junyanz** [comment]
@samrudhdhirangrej  The code is correct as fake_B_random = netG(real_A_encoded, z_random), which means fake_B_random corresponds to real_A_encoded.

@eveningglow Given the same real image A, we sample a random vector z and produce a fake output (fake_B_random). This implements G(A, z) in Eqn (7) in the paper. Of course, one can also use real_A_random as input for Eqn (7).  (let's denote A1=A_encoded and A2=A_random)
In our implementation, we ask D to classify (A1, G(A1, z)) vs. (A2, B2). 
In the alternative case, D aims to classify (A2, G(A2, z)) vs. (A2, B2). 
In practice, we find that the first implementation can produce slightly more diverse results, as we are mixing different input-output pairs and styles.  

Sorry that the naming of the variables could be improved. (Maybe A1, A2 might be better) 
@pathak22  Maybe Deepak can explain the intuition better.

**Comment by eveningglow** [comment]
@junyanz Thank you for your explanation!
