### ISSUE TITLE
About Encoder

### ISSUE THREAD

**Issue by mathfinder** [junyanz/BicycleGAN#15]
line 682 and 683 in class E_ResNet in models/networks.py :
input_ndf = ndf * min(max_ndf, n)  # 2**(n-1)
output_ndf = ndf * min(max_ndf, n+1)  # 2**n

The code and code comment are not consistent. The multiplier of the number of first filters is not growing exponentially.

**Comment by junyanz** [comment]
We tried an encoder with the exponential number of filters but did not see a big difference regarding the performance. I guess the skip connection in the ResNet block might help. 
We used the following code before, and later I commented the code out: 
```python
input_ndf = ndf * min(max_ndf, 2**(n-1))
output_ndf = ndf * min(max_ndf, 2**n)
```
I will update the comment.

**Comment by mathfinder** [comment]
@junyanz , Thx for your code and reply. And I wonder if the discriminator of residual network form can improve its performance?

**Comment by junyanz** [comment]
ResNet discriminator might be too strong sometimes. You also need to have a stronger generator to match the capacity.
