### ISSUE TITLE
Can I use my own data for training?

### ISSUE THREAD

**Issue by happsky** [junyanz/BicycleGAN#16]
Can I use my own data for training?

**Comment by junyanz** [comment]
Absolutely. You can use the [script](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/datasets/combine_A_and_B.py) we provided in the pix2pix repo. See [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix#pix2pix-datasets) for the instruction.
