### ISSUE TITLE
RuntimeError: size mismatch , when using my own 512x512 dataset

### ISSUE THREAD

**Issue by lxj616** [junyanz/BicycleGAN#17]
`python train.py --dataroot ./datasets/maps --name maps_bicyclegan --model bicycle_gan --display_id 0 --nThread 0 --loadSize 512 --fineSize 512 --display_winsize 512 --which_direction 'AtoB' --use_dropout --gpu_ids 0`

```
model [BiCycleGANModel] was created
create web directory ./checkpoints/maps_bicyclegan/web...
Traceback (most recent call last):
  File "train.py", line 25, in <module>
    model.update_D(data)
  File "/workdir/BicycleGAN/models/bicycle_gan_model.py", line 120, in update_D
    self.forward()
  File "/workdir/BicycleGAN/models/bicycle_gan_model.py", line 43, in forward
    self.mu, self.logvar = self.netE.forward(self.real_B_encoded)
  File "/workdir/BicycleGAN/models/networks.py", line 697, in forward
    output = self.fc(conv_flat)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/linear.py", line 55, in forward
    return F.linear(input, self.weight, self.bias)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/functional.py", line 835, in linear
    return torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch at /pytorch/torch/lib/THC/generic/THCTensorMathBlas.cu:243
```

tested 256x256 works fine, but any other size would raise the exception above 
I am not good enough to fix this on my own after hours ...

**Comment by junyanz** [comment]
The current Encoder network (E_ResNet) only supports 128x128 (`--which_model_netE resnet_128`) and 256x256 (`--which_model_netE resnet_256`). But you can simiply add one line after this [line](https://github.com/junyanz/BicycleGAN/blob/master/models/networks.py#L197). 
```python
 elif which_model_netE == 'resnet_512':
        netE = E_ResNet(input_nc, output_nc, ndf, n_blocks=6, norm_layer=norm_layer,
                        nl_layer=nl_layer, gpu_ids=gpu_ids, vaeLike=vaeLike)
```

**Comment by riktimmondal** [comment]
i think the above lines of code is needed to be added in define_E function .But doing so throws error where net is of type None which is being passed to the init_net function.
It will be kind of you if clearly state how to use bycycle gan for 512*512 dataset

**Comment by rickkk856** [comment]
> The current Encoder network (E_ResNet) only supports 128x128 (`--which_model_netE resnet_128`) and 256x256 (`--which_model_netE resnet_256`). But you can simiply add one line after this [line](https://github.com/junyanz/BicycleGAN/blob/master/models/networks.py#L197).
> 
> ```python
>  elif which_model_netE == 'resnet_512':
>         netE = E_ResNet(input_nc, output_nc, ndf, n_blocks=6, norm_layer=norm_layer,
>                         nl_layer=nl_layer, gpu_ids=gpu_ids, vaeLike=vaeLike)
> ```

Is this [line](https://github.com/junyanz/BicycleGAN/blob/master/models/networks.py#L197) up to date?
comment was on mar 2018

and last update was on 6 Jan 2019. 
Its not working for me. I have the same issue 512x512 pixels - 800images dataset `preprocess none`
