### ISSUE TITLE
Is possible to generate labels from facades images?

### ISSUE THREAD

**Issue by happsky** [junyanz/BicycleGAN#18]
Is possible to generate labels from facades images?
We tried both --which_direction B2A and --which_direction A2B, but the results are the same, is there anything I missed?
Thanks a lot!

**Comment by junyanz** [comment]
This repo (BiCycleGAN) focuses on one-to-many problems, which is not the case in facades->labels. 
I think the code should still work if you change the `--which_direction`. Could you share with us your script?
Please [pix2pix](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix) for facades->labels problem.
