### ISSUE TITLE
Training on Piano Roll data

### ISSUE THREAD

**Issue by rafaelvalle** [junyanz/BicycleGAN#28]
Hey Jun-Yan, thanks for putting this repo together.
I'm trying to train it on piano roll data and have been seeing unexpected behavior: the generator outputs the same image even though the conditions, i.e. noise vector and real A, change.

Any thoughts on what it could be? I've added the loss log, options, output images during training and output images during inference.

[loss_log.txt](https://github.com/junyanz/BicycleGAN/files/2147861/loss_log.txt)
[opt.txt](https://github.com/junyanz/BicycleGAN/files/2147862/opt.txt)

Model outputs during training(fake_b_encoded, fake_b_random, real_a_encoded,real_b_encoded)
![fake_b_encoded](https://user-images.githubusercontent.com/2302607/42074378-d82dedb8-7b20-11e8-810d-3f99889d13d4.png) ![fake_b_random](https://user-images.githubusercontent.com/2302607/42074380-d8499482-7b20-11e8-91f5-c07316f747f5.png) ![real_a_encoded](https://user-images.githubusercontent.com/2302607/42074381-d862972a-7b20-11e8-9bdf-db1addc35073.png) ![real_b_encoded](https://user-images.githubusercontent.com/2302607/42074382-d87a3ff6-7b20-11e8-85a0-eb33c53cf032.png)

```
model.set_input(data)
encode = False
z_samples = model.get_z_random(1, opt.nz)
real_A, fake_B, real_B = model.test(z_samples, encode=encode)
```
Model outputs during inference(real_a, real_b, fake_b)

![iModel output during inference](https://user-images.githubusercontent.com/2302607/42074368-c86b148c-7b20-11e8-9e5f-a2ce9b8caa7d.png)

**Comment by junyanz** [comment]
I am not familiar with the piano roll data. Is it for future prediction?   The current generator architectures assume strong spatial alignment between input and output, which might not be the case of your application. It also seems that L1 reconstruction does not work for your application as most of the pixels are black.

**Comment by rafaelvalle** [comment]
Yes, it is for future prediction. Does the spatial alignment come from the concatenation of features?
With other architectures L1 didn't seem to help...

**Comment by junyanz** [comment]
Our generator architecture works well for spatially aligned data. It might be struggling for other types of data.

**Comment by rafaelvalle** [comment]
What in your generator's architecture makes it work well for spatially aligned data?

**Comment by junyanz** [comment]
The generator is a [U-Net](https://arxiv.org/pdf/1505.04597.pdf) with many skip connections. Please see the original paper for more details. Also, check out Sec 3.2.1 in the pix2pix [paper](https://arxiv.org/abs/1611.07004).

**Comment by rafaelvalle** [comment]
Thank you for pointing out the section in the paper. I'll close the issue.
