### ISSUE TITLE
Training cLR-GAN or cVAE-GAN

### ISSUE THREAD

**Issue by myway0101** [junyanz/BicycleGAN#29]
Hi, 
Thank you very much for sharing this fantastic work!
I would like to train a model,  cLR-GAN or cVAE-GAN.
I think the default setting is MODEL='bicycle_gan'.
Is there any way to train each model?

Thank you!

**Comment by junyanz** [comment]
You can do it by changing the lambda hyper-parameter. 
For cLR-GAN: set `--lambda_GAN 0` and `--lambda_kl 0`.
For cVAE-GAN:  set `--lambda_GAN2 0` and `--lambda_z 0`.

**Comment by myway0101** [comment]
Thank you very much for your response!
It is very simple :)

**Comment by myway0101** [comment]
Hi, 

Thank you for sharing your great work!

As your above suggestion, I try to train cVAE-GAN model by setting --lambda_GAN2 0 and --lambda_z 0.
python .\train.py^
 --display_id 1^
 --dataroot .\datasets\polyp_612^
 --model bicycle_gan^
 --which_direction BtoA^
 --checkpoints_dir .\checkpoints\polyp_612\^
 --loadSize 256^
 --fineSize 256^
 --nz 8^
 --input_nc 1^
 --niter 30^
 --niter_decay 30^
 --use_dropout^
 --lambda_GAN2 0^
 --lambda_z 0

But, I got this error:
create web directory .\checkpoints\polyp_612\web...
Traceback (most recent call last):
  File ".\train.py", line 36, in <module>
    model.optimize_parameters()
  File "E:\BicycleGAN\models\bicycle_gan_model.py", line 212, in optimize_parameters
    self.update_G_and_E()
  File "E:\BicycleGAN\models\bicycle_gan_model.py", line 200, in update_G_and_E
    self.backward_EG()
  File "E:\BicycleGAN\models\bicycle_gan_model.py", line 156, in backward_EG
    self.loss_G_GAN2 = self.backward_G_GAN(self.fake_data_random, self.netD2, self.opt.lambda_GAN2)
AttributeError: 'BiCycleGANModel' object has no attribute 'netD2'

If I train original model(BicycleGAN), i.e., didn't set --lambda_GAN2 and --lambda_z, training is working.

Could you help me solve this problem or any other way to train cVAE-GAN model?

Thank you.
