### ISSUE TITLE
python3 and slice indices must be integers...

### ISSUE THREAD

**Issue by htoyryla** [junyanz/BicycleGAN#3]
Tried training (based on my experience with pytorch-CycleGAN-pix2pix), my pytorch setup is based on python 3.6. Got error "slice indices must be integers or None or have an __index__ method" because of the division at line https://github.com/junyanz/BicycleGAN/blob/master/models/bicycle_gan_model.py#L35

I suggest adding explicit conversion to int at this line.

**Comment by junyanz** [comment]
Thanks for reporting the issue. I just fixed the issue. Still working on a better version of training code.
