### ISSUE TITLE
About val data

### ISSUE THREAD

**Issue by holylone** [junyanz/BicycleGAN#32]
Hi, thanks for your amazing work.
I train the network with my own database, it works well.
However, I don't have so many data for training(just about 700 images).
My question is 
1. How many data should I put in the val folder? Or, the val folder is just for testing the network? 
2. Besides the paired data, I also have some unpaired data, for example, (Many B but lack of A, training direction: A2B), let me know if you are consider an algorithm for such semi-supervised situation. 

Thanks.

**Comment by lxj616** [comment]
1. The val folder is just for testing the network
2. Try cyclegan https://github.com/junyanz/CycleGAN , BicycleGAN adds bidirectional cycle-consistency losses to "discover multiple modes"

**Comment by holylone** [comment]
@lxj616 Thanks for replying.
I tried cyclegan, the network can only generate one sample between domain A and B.
However, I want to generate many kinds of B from A, corresponding to diversity of B. The problem is a lot of B, but no A. Any idea of this? 
I have another question, I was test BicycleGan on exist paired dataset. The generated B are diverse. But some images are quite strange like some net is added. Are there some way to deal with this?
![image](https://user-images.githubusercontent.com/41974263/43507442-16449c22-95a8-11e8-9bde-24d509c12240.png)
|z|: 4 (Diversity is lost at |z|=2)

**Comment by junyanz** [comment]
See these two papers for the multimodal image-to-image translation in the unpaired case: 
[Augmented CycleGAN](https://arxiv.org/abs/1802.10151)
[MUNIT](https://arxiv.org/abs/1804.04732)

**Comment by holylone** [comment]
@junyanz Thanks for replying.
The MUNIT didn't work very well.
The dataset A contains only binary images like circuit pattern. Because of the diversity of the dataset B,  I think it difficult to train the network only use the unsupervised learning.
Maybe I need to train the unpaired data using the pretrained network trained by paired data.

**Comment by junyanz** [comment]
Adding paired data often helps constrain the problem. Good luck with your project.
