### ISSUE TITLE
Unexpected pdb debugger trace statement in commit

### ISSUE THREAD

**Issue by lxj616** [junyanz/BicycleGAN#35]
Hi, in your commit
https://github.com/junyanz/BicycleGAN/commit/219b3f98001448eff5f2cbb5467940b6a2bfb4fe
there are lots of `import pdb; pdb.set_trace()` debugger statement within code
```
   def forward(self):
        # get real images
        half_size = self.opt.batchSize // 2
        half_size = self.opt.batch_size // 2
        import pdb; pdb.set_trace()
        # A1, B1 for encoded; A2, B2 for random
```

I am not sure if this is intended, or just forgot to remove them after debug?

**Comment by junyanz** [comment]
It was my mistake. I just removed them.
