### ISSUE TITLE
Is there any reason why relu is the default option?

### ISSUE THREAD

**Issue by MakeDirtyCode** [junyanz/BicycleGAN#36]
I wonder why you used relu as a non-linear function as the default option. I know many models are using leaky relu, is there any reason why relu is the default option? Has the experiment proved better results?

**Comment by junyanz** [comment]
We follow the practice in [DCGAN](https://github.com/pytorch/examples/tree/master/dcgan) code. We use the relu for G and the leakly relu for D (see this [line](https://github.com/junyanz/BicycleGAN/blob/master/models/networks.py#L122))

**Comment by MakeDirtyCode** [comment]
Thank you for your reply
