### ISSUE TITLE
About disentangled representation of latent code z

### ISSUE THREAD

**Issue by holylone** [junyanz/BicycleGAN#37]
Hi, thanks for your amazing work.
I have trained the model with my own dataset, and generated multi-style samples corresponding input with different latent code z.

However, I felt it is difficult to generate the specific style sample. It is very painful that read the mapping of latent code z.
Is it possible to disentangle latent code z by adding mutual information?  Or there is any method to solve this?

**Comment by junyanz** [comment]
Sorry for the late reply. I guess one method is to use a style guidance image x. You can get the style code using the encoder E(x). If you have annotated attributes data (e.g., face attributes for face images), you can train a model directly. See the attribute2image [paper](https://arxiv.org/abs/1512.00570). Also, [InfoGAN](http://papers.nips.cc/paper/6399-infogan-interpretable-representation-learning-by-information-maximizing-generative-adversarial-nets.pdf) is related to what you are looking for.
