### ISSUE TITLE
About conditioning the discriminator

### ISSUE THREAD

**Issue by r06922019** [junyanz/BicycleGAN#38]
Hi,

In Section 4 Implementation Details 
> **Training details** ...
> We also find that not conditioning the discriminator D on input A leads to
> better results (also discussed in [34]), ...

Does this means that the discriminator has no information to ensure the generated image to be conditioned on image A? 
Say we are generating shoes from edges. Being unconditioned on the input image (edges), the discriminator should only be able to tell if the generated shoes are real/fake, but not able to tell if the generated shoes doesn't match the conditions (edge)?
Or some other mechanism is working on the condition part?

Looking forward to your reply, thanks! Nice work!

**Comment by junyanz** [comment]
We also have the L1 image reconstruction to enforce the correspondence.

**Comment by r06922019** [comment]
I see. Thanks for your reply.
