### ISSUE TITLE
how was wgan-gp used in the network?

### ISSUE THREAD

**Issue by windforever118** [junyanz/BicycleGAN#43]
I noted that there is a function cal_gradient_penalty in your code, but it seems that you didn't use it?

**Comment by lc82111** [comment]
I have tried the wgan-gp, but the performance is terrible. Then, I switched to spectral Norm wgans, and it seems good.

**Comment by junyanz** [comment]
wgan-gp was not used in the original paper. Just add it in case people like to do experiments.

**Comment by windforever118** [comment]
I have also tried to apply wgan-gp to my network, but the results were even worse. So I am a liitle interested in how it can be used in the network. Thank you, maybe I should try another way.

**Comment by dingyineversad** [comment]
> I have tried the wgan-gp, but the performance is terrible. Then, I switched to spectral Norm wgans, and it seems good.



> I have tried the wgan-gp, but the performance is terrible. Then, I switched to spectral Norm wgans, and it seems good.

Can I see your improvement code of bicyclegan? Thank you very much
