### ISSUE TITLE
Adding information to BicycleGAN network

### ISSUE THREAD

**Issue by ic97usop** [junyanz/BicycleGAN#47]
As far as I understood the paper, it is possible to add images and additional information to G and D in BicycleGAN. Is this possible to achieve this by using the add_to_input function? If so, where do I set the number and the path of the additional information? Otherwise, which function should be used for this purpose?

Thank you in advance.

**Comment by junyanz** [comment]
Not sure if `add_to_input` function is included in this repo. To add images, you can implement your custom data [loader](https://github.com/junyanz/BicycleGAN/blob/master/data/template_dataset.py). To add additional information, you need to modify the G and [network](https://github.com/junyanz/BicycleGAN/blob/master/models/networks.py) definition.

**Comment by ic97usop** [comment]
Thank you. I guess that in this repo the function add_to_input is represented by the class G_add_to_input in networks.py. However, no additional Information can be introduced into the discriminator. Is that actually the way how the network should work?

**Comment by junyanz** [comment]
Regarding discriminator, to add images, you can concatenate all your images into a single one and feed it to the discriminator (You need to also change the input dimensions when you construct the discriminator). To add additional information, you need to write a new discriminator.

**Comment by ic97usop** [comment]
Is it also possible to pass additional parameters to G that are not images? For instance, if each image is taken at a certain velocity, is it possible to convolve the image with a double value (representing the velocity) and then to pass the result to the generator?
