### ISSUE TITLE
Issue while running test.py

### ISSUE THREAD

**Issue by a7b23** [junyanz/BicycleGAN#51]
Hi, I am getting the following error when running the code. I am using python3.6 and have installed the latest pytorch version(1.0).
![screenshot from 2019-03-01 19-35-51](https://user-images.githubusercontent.com/12389081/53644106-c49fac80-3c5b-11e9-8ece-52410aa5d2e7.png)

Could you suggest the issue involved ?

**Comment by Ibrahim788** [comment]
I'm running into the same issue. I had it working with the edge2handbags dataset then that broke too the next time a pulled down the code base. Any luck solving the issue?

**Comment by fishzhouz** [comment]
yeah,that is exactly what I've met.A few days ago,I runned this pre-trained model,it works out on edges2shoes . but in recently days ,It seems broken, as this same problem,Have you fixed that?How?

**Comment by shazhongcheng** [comment]
i also meet this question,and i really dont know how to fix it……so sad

**Comment by htoyryla** [comment]
Without having deeper knowledge of this project, a mismatch between [1, 256, 256] and [3, 256, 256] could be due to using a greyscale image where an RGB image is expected (and that the software is not built to handle this gracefully). I would suggest that you ensure, whenever you get this error, that all images used are of the correct type, and modify them if not.

**Comment by fishzhouz** [comment]
> Without having deeper knowledge of this project, a mismatch between [1, 256, 256] and [3, 256, 256] could be due to using a greyscale image where an RGB image is expected (and that the software is not built to handle this gracefully). I would suggest that you ensure, whenever you get this error, that all images used are of the correct type, and modify them if not.

There are so many people have this problem.It can't be the picture's reason,OK? I can't convince you before you clone this project and use it. A few days age, it worked out .However,It doesn't work totally!
As you said , you have very deep knowledge of this project? OK ,here is the question:why are these two class different from input_layer? fix it , handsome bro!
![NM{Q3_7~8Y KZ9QID7A YPQ](https://user-images.githubusercontent.com/34651117/54196382-3dc0be80-44fc-11e9-9807-e1b63245ad3a.png)
![_PG8DU O06` V8J4WUBVO$K](https://user-images.githubusercontent.com/34651117/54196400-4addad80-44fc-11e9-940d-5c3f8f002a41.png)

**Comment by htoyryla** [comment]
I said "without deeper knowledge" of this particular project, just wanted to point out that similar mismatches are usually indicate that an input image has wrong number of channels, like greyscale when rgb is expected or vice versa. Something one must constantly be aware of when working with images on this level. If you train a model to take rgb images but then feed it a grayscale image, or vice versa, you will get a mismatch.

If me stating this makes you irritated, I can remove my comment and refrain from commenting in the future. 

As to the two classes, looks like the one uses rgb images while the other one grayscale images.

**Comment by fishzhouz** [comment]
My account was lost,the comment above was not from my hands.I'm sorry to the cute stranger.~

**Comment by htoyryla** [comment]
Looks like there's been changes recently to nc handling 

https://github.com/junyanz/BicycleGAN/commit/a7d3ed3eba8f2b7a8143e7a4f35bfbd22ddfa2ca#diff-ed1377284a526e0e538bf75912429515R24:25

so the error could be due to code changes.

**Comment by fishzhouz** [comment]
> Looks like there's been changes recently to nc handling
> 
> [a7d3ed3#diff-ed1377284a526e0e538bf75912429515R24:25](https://github.com/junyanz/BicycleGAN/commit/a7d3ed3eba8f2b7a8143e7a4f35bfbd22ddfa2ca#diff-ed1377284a526e0e538bf75912429515R24:25)
> 
> so the error could be due to code changes.

Hello,do you remember me?But I'm not the one who argued with you just now.My account was lost.I,m sorry to you.~

**Comment by junyanz** [comment]
Would it be possible to share with me more details? Are you using the latest code?  I ran the following code and haven't been able to reproduce this error. 
```bash
bash ./datasets/download_testset.sh edges2shoes
bash ./pretrained_models/download_model.sh edges2shoes
bash ./scripts/test_edges2shoes.sh
bash ./scripts/train_edges2shoes.sh
```

**Comment by junyanz** [comment]
Hi folks, could you try the latest commit? Hopefully, it can address your issues.
