### ISSUE TITLE
An error in `UnetBlock_with_z`

### ISSUE THREAD

**Issue by TropComplique** [junyanz/BicycleGAN#52]
The way you inject noise in `UnetBlock_with_z` is possibly ineffective. 

Let's consider an example:
```python
import torch
import torch.nn as nn

s = 16
x = torch.rand(1, 10, s, s)
p = 0

# your downsampling block
down = nn.Sequential(
    nn.LeakyReLU(0.2),
    nn.Conv2d(18, 10, kernel_size=4, stride=2, padding=p),
    nn.InstanceNorm2d(10)
)

z = torch.rand(1, 8)  # noise
z_img = z.view(z.size(0), z.size(1), 1, 1).expand(z.size(0), z.size(1), x.size(2), x.size(3))

x_and_z = torch.cat([x, z_img], 1)
y = down(x_and_z)
```

`y` doesn't depend on `z` if `p` is equal to zero.
If `p` is equal to 1 and `s` is large (~128) then `y` changes in some weird way.

I am talking about this part of your code:
https://github.com/junyanz/BicycleGAN/blob/master/models/networks.py#L729

**Comment by junyanz** [comment]
I think y still depends on the z, as there is a conv2d layer before instancenorm. The conv2d layer will mix and z. Recent methods [[1](https://arxiv.org/abs/1804.04732)] [[2](https://arxiv.org/pdf/1903.07291.pdf)] have better ways to mix two variables x and z.
