### ISSUE TITLE
what is this means?

### ISSUE THREAD

**Issue by fishzhouz** [junyanz/BicycleGAN#53]
![GMDQ_LVP0YS78IY~@ $@3{W](https://user-images.githubusercontent.com/34651117/54070764-2769f700-429f-11e9-9cf3-448d656c861a.png)

I cann't train and use a pre-trained model because of this reason? Have any one fix it ？

**Comment by ic97usop** [comment]
What is the number of your input and output channels?

**Comment by junyanz** [comment]
Would it be possible to share with me your command line?

**Comment by junyanz** [comment]
Would it be possible to share with me more details? Are you using the latest code? What is the PyTorch and Python version? I ran the following code and haven't been able to reproduce this error. 
```bash
bash ./datasets/download_testset.sh edges2shoes
bash ./pretrained_models/download_model.sh edges2shoes
bash ./scripts/test_edges2shoes.sh
bash ./scripts/train_edges2shoes.sh
```

**Comment by junyanz** [comment]
Hi folks, could you try the latest commit? Hopefully, it can address your issues.
