### ISSUE TITLE
About EOFError: Ran out of input

### ISSUE THREAD

**Issue by cutewss** [junyanz/BicycleGAN#57]
Hello , sorry to bother you. Could you please help me to fix this problem? When I run the command that bash ./scripts/test_edges2shoes.sh
I got the following error:

File "/home/ysgx/.local/lib/python3.6/site-packages/torch/serialization.py", line 368, in load
    return _load(f, map_location, pickle_module)
  File "/home/ysgx/.local/lib/python3.6/site-packages/torch/serialization.py", line 532, in _load
    magic_number = pickle_module.load(f)
EOFError: Ran out of input

![图片](https://user-images.githubusercontent.com/49510061/56293346-7be47a00-615b-11e9-896a-d55eb6220ef6.png)
Does that mean there is something wrong with my installation of Pytorch?
I look forward to receiving your reply as soon as possible.
Thank you very much.

**Comment by junyanz** [comment]
I would check if the model file is not empty first. Have you downloaded the pre-trained model? Please see more details in the [README](https://github.com/junyanz/BicycleGAN#use-a-pre-trained-model).

**Comment by xuzhongyou** [comment]
sorry, the dataset and pretrained model can not be downloaded, can u give other address?

**Comment by junyanz** [comment]
Have you tried `bash ./pretrained_models/download_model.sh edges2shoes`? It works for me. 
The models are under `http://efrosgans.eecs.berkeley.edu/BicycleGAN//models/`.

**Comment by xuzhongyou** [comment]
Thank you, i works again. May be the internet speed problem.
