### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by KongCang** [junyanz/BicycleGAN#59]
$ bash ./datasets/download_testset.sh edges2shoes
./datasets/download_testset.sh: line 5: wget: command not found
mkdir: cannot create directory ‘./datasets/edges2shoes/’: File exists
tar (child): ./datasets/edges2shoes.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
rm: cannot remove './datasets/edges2shoes.tar.gz': No such file or directory

**Comment by lxj616** [comment]
You need to install wget command first
Ubuntu: apt install wget
RHEL: yum install wget

**Comment by junyanz** [comment]
you may also want to remove `‘./datasets/edges2shoes/` directory.

**Comment by KongCang** [comment]
Thanks!
