### ISSUE TITLE
The result was not very good.

### ISSUE THREAD

**Issue by kiraracreams** [junyanz/BicycleGAN#62]
I trained a task of coloration use my own dataset about 22000,but the result was not very good.specially,when input random_z,the result is very bad.I've already trained about 130 epoch,should I train more epoch？Can we improve the results if we increase the weight of kl?.Could you give me some suggestion, thanks.
![image](https://user-images.githubusercontent.com/37492417/58182422-26623680-7ce0-11e9-82d7-a145fa367ecd.png)
![_images (1)](https://user-images.githubusercontent.com/37492417/58182457-3843d980-7ce0-11e9-925f-e3ac2db5c78e.jpg)
![_images (2)](https://user-images.githubusercontent.com/37492417/58182853-ed769180-7ce0-11e9-8270-9f05b5426f15.jpg)

**Comment by junyanz** [comment]
You can try different lambda KL losses. I also recommend that you use a network architecture tailored for manga colorization (e.g., this [one](https://github.com/lllyasviel/style2paints)).  It seems that your sketch input is also not perfect. (e.g., the first example)

**Comment by kiraracreams** [comment]
Thanks for your answer.
