### ISSUE TITLE
about fake_B_random

### ISSUE THREAD

**Issue by kiraracreams** [junyanz/BicycleGAN#64]
I trained a task of coloration use my own dataset about 22000,last time,i can't get good result both fake_B_encoded and fake_B_random.now I add nosie into middle layer and nz=512,although fake_B_encoded is good,checkerboard artifacts of fake_B_random is very serious,I attemp to use upsampling+conv,but the effect has not improved.Is it a problem of too few datasets?,and the task of coloration is complex.so it lead the Encoder can not encode pictrue in a continuous space.could you give me some suggestion?
![_images (6)](https://user-images.githubusercontent.com/37492417/59353089-c5fd6c80-8d54-11e9-97ec-2a8de95233c8.jpg)
![_images (7)](https://user-images.githubusercontent.com/37492417/59353100-cc8be400-8d54-11e9-9f22-4a4846ebc854.jpg)

**Comment by SanderGielisse** [comment]
I think nz=512 is too high, it simply overfits. On data it knows, it has a perfect latent representation, which leads to a perfect coloration. On a random latent vector the network is unable to produce anything sensible. But please correct me if I am wrong on this :)

**Comment by junyanz** [comment]
The results look quite diverse for me. To improve the quality of the results, you are welcome to try recent methods such as [pix2pixHD](https://github.com/NVIDIA/pix2pixHD) and [SPADE](https://github.com/NVlabs/SPADE).
`nz=512` might be a little too high. Try smaller nz.

**Comment by kiraracreams** [comment]
Thanks for your answer!
I try to smaller nz and higher lambda_kl,because nz is too high,to avoid gradient explosion I set lambda_kl = 0.0001.

**Comment by junyanz** [comment]
Good luck!
