### ISSUE TITLE
When to use drop out?

### ISSUE THREAD

**Issue by SanderGielisse** [junyanz/BicycleGAN#65]
To my understanding, the paper does not use dropout in the experiments. I feel like dropout in the generator could be useful for pix2pix for instance, to allow multiple different outputs for a single given input. All the scripts in this project use dropout by default, but I wonder why. Isn't the one-to-many mapping problem already solved by adding the latent vector?

Thanks in advance.

**Comment by junyanz** [comment]
We used Dropout to prevent overfitting.

**Comment by SanderGielisse** [comment]
Ah, Thanks for the quick response!
