### ISSUE TITLE
Ambiguous about one-to-many

### ISSUE THREAD

**Issue by viethungtsdv** [junyanz/BicycleGAN#68]
Dear Junyanz,
Currently, I really ambiguous about objective in your paper. The output is many styles or many images that have same only one style.

Thank you very much.

**Comment by junyanz** [comment]
It depends on your definition of style. If style=domain. the output is many possible images for the same domain.

**Comment by viethungtsdv** [comment]
Dear @junyanz, thanks for reply. In case I want to domain A has only one style and domain B has many styles (one-to-many). How to settings and modify your code to match my expectation?
Thank you very much.

**Comment by junyanz** [comment]
It seems that the definition of your style is not the same as the domain. In your current definition, you can use the code directly.

**Comment by viethungtsdv** [comment]
Thank for your answer.
