### ISSUE TITLE
A little question for latent code z.

### ISSUE THREAD

**Issue by remega** [junyanz/BicycleGAN#69]
Hi, Junyanz

I have a little question for the L1-loss on latent code z (see the link: https://github.com/junyanz/BicycleGAN/blob/a3c7c78f866029637eaa8adacf171967e4182c56/models/bicycle_gan_model.py#L186).  Is there any reseaon why using mu2 for l1 loss, but not using the encoded z vector like that in self.encode(), which considers the logvar as well? 

I would appreciate much if you could help.

Best,
Lai

**Comment by junyanz** [comment]
self. z_encoded might also work. But it will be less stable as z_encoded depends on the random variable [eps](https://github.com/junyanz/BicycleGAN/blob/master/models/bicycle_gan_model.py#L84).

**Comment by remega** [comment]
I see. Thanks for your reply.
