### ISSUE TITLE
D_NLayersMulti implementation correctness

### ISSUE THREAD

**Issue by SanderGielisse** [junyanz/BicycleGAN#71]
Hi,

I wonder whether the implementation of class D_NLayersMulti is correct. I got two problems I have trouble understanding.

1. Defining --num_ds as 2 actually uses a single discriminator since "for i in range(1, num_D)" in networks.py starts at 1, and thus only executes the loop a single time.
2. When using multiple discriminators, the number of filters is varied, not the amount of layers. Changing the amount of filters does nothing to the patch size, only to the complexity of the network. I believe from [this issue](https://github.com/phillipi/pix2pix/issues/49) this is not how using multiple discriminators is intended.

Could this please be clarified? Thanks in advance.

**Comment by junyanz** [comment]
1. We have added `model_0` before going into the FOR loop. See this [line](https://github.com/junyanz/BicycleGAN/blob/master/models/networks.py#L202).
2. The number of layers is the same. But for each discriminator, we downsample the images by different amounts. See this [line](https://github.com/junyanz/BicycleGAN/blob/master/models/networks.py#L203) for downsampling code.
