### ISSUE TITLE
Using z as an extra label

### ISSUE THREAD

**Issue by yjs0704** [junyanz/BicycleGAN#72]
Hi thanks for the excellent code.

I want to use z as an extra label other than A, by initialising it with a given vector and removing the VAE loss. Some other modifications might involve using NON-VAE mode in z generations and adding extra loss between input_z and encoded_z.  Does it make any sense to you?

Thanks again.

**Comment by junyanz** [comment]
I am not sure if it will work. But feel free to try it.

**Comment by yjs0704** [comment]
Thanks for the reply.
