### ISSUE TITLE
different image size not supported.

### ISSUE THREAD

**Issue by SuborbitalIndian** [junyanz/BicycleGAN#75]
Dear @junyanz,
Thank you very much for the great share. I have size mismatch error when training for other than 256x256 image size. Here is the command for training the model that fails.
`python train.py --dataroot /data/random_tiles_1536 --name denoising_final_2 --model bicycle_gan --direction BtoA --netG unet_256 --norm instance --input_nc 1 --output_nc 1 --load_size 1536 --crop_size 256 --display_winsize 1536`

if I change --crop_size to any other value i.e. 1024 then shape mismatch

**Comment by junyanz** [comment]
The current `unet_256` only supports `256x256` input. You need to modify the network and add a few layers to support  `1024x1024` input. 

Alternatively, you can use other networks, such as `resnet_9blocks` used in CycleGAN/pix2pix [repo](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/models/networks.py#L150). The resnet has not been included in this repo but you can copy and paste the network architecture from that repo.
