### ISSUE TITLE
question about the evaluation metrics of diversity

### ISSUE THREAD

**Issue by ForawardStar** [junyanz/BicycleGAN#76]
Hi, 
 I think it is really an excellent work. Here I have a question about the evaluation metrics of diversity. What the paper says is that "we compute the average distance between 1900 pairs of randomly generated output" . Does it mens the distance is calculated by each output and the corresponding groud truth, or by each output and the input image, or by any two outputs? If the former is the case， what if the datasets is unpaired or have no ground truth?
   Thanks

**Comment by richzhang** [comment]
It's the average distance between two randomly generated outputs.

**Comment by ForawardStar** [comment]
ok, Thank you
