### ISSUE TITLE
Why we use 'retain_graph' when backwarding loss_G?

### ISSUE THREAD

**Issue by Imposingapple** [junyanz/BicycleGAN#81]
Dear authors,
thanks for sharing your amazing work.

I've read the code, and found two questions. Here comes the first one. 
In bicycle_gan_model, the last row of function 'backward_EG' specifies that we should retain graph when backwarding, I change the 'retain graph' option to false and no error occurs. I would like to ask whether we should specifies 'retain graph' option to be true?

**Comment by junyanz** [comment]
What is the value of your `lambda_z` ? I remember it might break in `backward_G_alone` without `retain graph`. We used to have more losses in `backward_G_alone`.

**Comment by Imposingapple** [comment]
Oh, I see. Thank you!
