### ISSUE TITLE
Question about PatchGAN perception field

### ISSUE THREAD

**Issue by Imposingapple** [junyanz/BicycleGAN#82]
Dear authors,
thanks for sharing your amazing work.

Here is my second question. 
I found that your paper said you use 70*70 and 140*140 PatchGAN as D. To my knowledge, 140*140 means that each cell has a 140*140 perception field in D output.
I've calculated the perception field by myself, the 70*70 PatchGAN is exactly right, but I came out with a 141*141 perception field in 140*140 PatchGAN. To my knowledge, we can calculate perception field in this way:
![1](https://user-images.githubusercontent.com/39848377/80090264-d0ea7580-8591-11ea-9d9d-2749623606fb.png)
So 
l_0=1
l_1=3
l_2=3+(4-1)*2=9
l_3=9+(4-1)*2*2=21
l_4=21+(4-1)*2*2*2=45
l_5=45+(4-1)*2*2*2*2=93
l_6=93+(4-1)*2*2*2*2*1=141

**Comment by Imposingapple** [comment]
Excuse me for using a graph in Chinese language.

**Comment by junyanz** [comment]
We used this [script](https://github.com/phillipi/pix2pix/blob/master/scripts/receptive_field_sizes.m).

**Comment by Imposingapple** [comment]
Thank you very much for answering my question. 

The two methods of calculating perception field may be different in form but same in answer as far as I have experimented. The n=4 discriminator of your script outputs 142. In the implement of your code, just refering to the default edges2shoes senario, you first use a 3 times 3 average pool instead of a kernel size of 4. So just modifying your script to accomodate with your bicycleGAN implementation in n=4 discriminator will also get a 141 times 141 perception field.

Here is the flow of 140 times 140 PatchGAN: 1. mid=down(input)   2. out=model_1
![1](https://user-images.githubusercontent.com/39848377/80182707-0ea2d900-863a-11ea-87d7-5a01133dee74.png)
(mid) 
Is my understanding correct? (just for better understanding the usage of PatchGAN, since I feel there's no great difference in the performance between 140 patchGAN and 141 PatchGAN) Thank you again for answering!

**Comment by junyanz** [comment]
You are correct. We will update it in the future version.
