### ISSUE TITLE
Question about conditional_D implementation

### ISSUE THREAD

**Issue by SanderGielisse** [junyanz/BicycleGAN#84]
In bicycle_gan_model.py there is a section that enables the conditional discriminator which is as following.
`
            self.fake_data_encoded = torch.cat([self.real_A_encoded, self.fake_B_encoded], 1)
            self.real_data_encoded = torch.cat([self.real_A_encoded, self.real_B_encoded], 1)
            self.fake_data_random = torch.cat([self.real_A_encoded, self.fake_B_random], 1)
            self.real_data_random = torch.cat([self.real_A[half_size:], self.real_B_random], 1)
`

Why is self.real_A_encoded added for some and only self.real_A[half_size:] for the last one? Could you please clarify? Would help a lot, thank you!

**Comment by junyanz** [comment]
See #25.

**Comment by SanderGielisse** [comment]
Whoops, missed that one. Thanks a lot and my complements on your great research.

**Comment by junyanz** [comment]
We use the first half of images in the batch, as follows:
```python
 self.real_A_encoded = self.real_A[0:half_size]
```
