### ISSUE TITLE
Is there <pix2pix+noise> model code that can be directly run？ 

### ISSUE THREAD

**Issue by qsunyuan** [junyanz/BicycleGAN#96]
<img width="387" alt="1635407195(1)" src="https://user-images.githubusercontent.com/71776283/139210413-dd7b13ba-c32c-4382-8548-eb23bdede038.png">

**Comment by junyanz** [comment]
We didn't include this baseline in our repo. However, it should not be that hard to modify the [pix2pix_model](https://github.com/junyanz/BicycleGAN/blob/master/models/pix2pix_model.py) with our generators (that can take noises as input).
